services:
  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    ports:
      - "1883:1883"    # MQTT TCP
      - "8883:8883"    # MQTT SSL (optional)
      - "18083:18083"  # Dashboard
    environment:
      - EMQX_NAME=emqx
      - EMQX_LISTENER__TCP__EXTERNAL=1883
      - EMQX_DASHBOARD__DEFAULT_USER__PASSWORD=public
    restart: unless-stopped
